version: '3'
networks:
    reverse_proxy:
        external: true

volumes:
    data:
    files:

services:
    meshcentral:
        ports:
            - "8086:8086"
        restart: always
        container_name: meshcentral
        image: typhonragewind/meshcentral:latest
        environment:
            - HOSTNAME=reverseproxy.sobe.name     #your hostname
            - REVERSE_PROXY=172.17.0.2     #set to your reverse proxy IP if you want to put meshcentral behind a reverse proxy
            - REVERSE_PROXY_TLS_PORT=443
            - IFRAME=false    #set to true if you wish to enable iframe support
            - ALLOW_NEW_ACCOUNTS=true    #set to false if you want disable self-service creation of new accounts besides the first (admin)
            - WEBRTC=false  #set to true to enable WebRTC - per documentation it is not officially released with meshcentral, but is solid enough to work with. Use with caution
            - BACKUPS_PW=MyAwesomePasswordPleaseChangeMe #password for the autobackup function
            - BACKUP_INTERVAL=24 # Interval in hours for the autobackup function
            - BACKUP_KEEP_DAYS=10 #number of days of backups the function keeps
            - VIRTUAL_HOST=reverseproxy.sobe.name
            - VIRTUAL_PORT=8086
            - NODE_ENV=production
            - LETSENCRYPT_HOST=reverseproxy.sobe.name
            - LETSENCRYPT_EMAIL=ggmethos@autistici.org
        volumes:
            - ./meshcentral/data:/opt/meshcentral/meshcentral-data    #config.json and other important files live here. A must for data persistence
            - ./meshcentral/user_files:/opt/meshcentral/meshcentral-files    #where file uploads for users live
            - ./meshcentral/backups:/opt/meshcentral/meshcentral-backups     #Backups location
        networks:
            - reverse_proxy
